language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - py.test tests/ --cov=.
  - pycodestyle --exclude=.coveragerc --exclude=.travis.yml --exclude=.venv .
after_success:
  - coveralls
